### ISSUE TITLE
Errors apt

### ISSUE THREAD

**Issue by tathastu871** [Yonle/termux-proot#4]
![Screenshot_20211221-180112_Termux](https://user-images.githubusercontent.com/65007212/146975141-d7148fcc-0b7f-4886-afc4-64fdd82c12ff.jpg)

**Comment by Yonle** [comment]
For emulating termux inside termux, Use the first version of termux-proot.

(Execute this outside termux-proot environment)
```sh
# Download the file of 1st version of termux-proot
curl -sLo ~/termux-proot.sh https://github.com/Yonle/termux-proot/raw/v1.0.0/termux

# Change permission
chmod ~/termux-proot.sh

# Start sandbox
~/termux-proot.sh
```
