### ISSUE TITLE
Cannot download android-base

### ISSUE THREAD

**Issue by babaric-dev** [Yonle/termux-proot#5]
The link to download the android base in the script seems to be invalid. How can I download it?

Btw, please tell me how the android base is generated. I want to learn more.

Thanks!

**Comment by Yonle** [comment]
Hi. The android base is actually came from [termux-docker](https://github.com/termux/termux-docker).

I've been rarely using proot these days, so i couldn't really guarantee that it will work perfectly :)

**Comment by Yonle** [comment]
I may update the code sometime......

**Comment by Yonle** [comment]
Should fixed now. Please refetch the script and run again. Thanks for the report

**Comment by babaric-dev** [comment]
Whoa. Im stunned. Thanks for the super quick response + fix!
