### ISSUE TITLE
Non-working DNS

### ISSUE THREAD

**Issue by JesusChapman** [Yonle/termux-proot#6]
![image](https://user-images.githubusercontent.com/64093255/211442911-4c8161cd-bc18-4191-86a0-b33a6e36ba22.png)

Is it not possible to access the internet from here?

**Comment by Yonle** [comment]
README.md:

> ## Disadvantages
> **__DNS is static.__** Should using static resolver that located at /etc/hosts or /system/etc/hosts. You may need to echo unresolved-domain.com >> /system/etc/static-dns-hosts.txt and run /system/bin/update-static-dns to get your unresolved-domain.com work.

**Comment by Yonle** [comment]
You can run an HTTP proxy in your host, then in your guest (termux-proot), You can set `http_proxy`, and `https_proxy` environment variable to use your HTTP Proxy.

**Comment by JesusChapman** [comment]
> You can run an HTTP proxy in your host, then in your guest (termux-proot), You can set `http_proxy`, and `https_proxy` environment variable to use your HTTP Proxy.

can you give me an example please

**Comment by Yonle** [comment]
The following example is done with `tinyproxy`.

Outside proot environment, Start `tinyproxy`
```sh
~ $ tinyproxy
```

Then, inside proot environment (which, in this case is termux-proot):
```sh
~ $ export http{s,}_proxy=http://localhost:8888
~ $ YourCommandsHere
```

**Comment by JesusChapman** [comment]
> The following example is done with `tinyproxy`.
> 
> Outside proot environment, Start `tinyproxy`
> 
> ```shell
> ~ $ tinyproxy
> ```
> 
> Then, inside proot environment (which, in this case is termux-proot):
> 
> ```shell
> ~ $ export http{s,}_proxy=http://localhost:8888
> ~ $ YourCommandsHere
> ```

Thanks
